// Default songs data
export const allSongs = [
  {
    id: 0,
    title: "Love Hurts",
    artist: "Nazareth",
    duration: "4:25",
    src: "./audio/Nazareth   Love Hurts.mp3",
  },
  {
    id: 1,
    title: "Down Under",
    artist: "Ment At Work",
    duration: "4:15",
    src: "./audio/Men At Work   Down Under.mp3",
  },
  {
    id: 2,
    title: "Mirrors",
    artist: "Justin Timberlake",
    duration: "3:51",
    src: "./audio/Justin Timberlake   Mirrors.mp3",
  },
  {
    id: 3,
    title: "I Want to Know What Love Is",
    artist: "Foreigner",
    duration: "3:34",
    src: "./audio/Foreigner   I Want To Know What Love Is.mp3",
  },
  {
    id: 4,
    title: "Everything I Own",
    artist: "Bread",
    duration: "3:35",
    src: "./audio/Everything I Own.mp3",
  },
  {
    id: 5,
    title: "Blue",
    artist: "Eiffel 65",
    duration: "3:12",
    src: "./audio/Eiffel 65   Blue.mp3",
  },
  {
    id: 6,
    title: "Paradise",
    artist: "Coldplay",
    duration: "3:25",
    src: "./audio/Coldplay   Paradise.mp3",
  },
  {
    id: 7,
    title: "Tuesday",
    artist: "Burak Yeter",
    duration: "3:52",
    src: "./audio/Burak Yeter-Tuesday.mp3",
  },
  {
    id: 8,
    title: "Long Gone",
    artist: "Benjamin Todd",
    duration: "3:10",
    src: "./audio/Benjamin Todd-Long Gone.mp3",
  },
  {
    id: 9,
    title: "A Horse With no Name",
    artist: "America",
    duration: "2:43",
    src: "./audio/America   A Horse With No Name .mp3",
  },
  {
    id: 10,
    title: "Don't you know what you've got till it's gone",
    artist: "Cinderella",
    duration: "2:43",
    src: "./audio/Cinderella Don't Know What You Got (Till It's Gone).mp3",
  },
  {
    id: 11,
    title: "Where Are You Now?",
    artist: "Nazareth",
    duration: "2:43",
    src: "audio/Nazareth   Where Are You Now.mp3",
  },
  {
    id: 12,
    title: "Dilema",
    artist: "Nelly",
    duration: "2:43",
    src: "./audio/Nelly   Dilemma.mp3",
  },
  {
    id: 13,
    title: "Live is Life",
    artist: "Opus",
    duration: "2:43",
    src: "./audio/Opus   Live Is Life.mp3",
  },
  {
    id: 14,
    title: "The Nights",
    artist: "Avicii",
    duration: "2:43",
    src: "./audio/Avicii - The Nights.mp3",
  },
  {
    id: 15,
    title: "Another Day in Paradise",
    artist: "Phil Collins",
    duration: "2:43",
    src: "./audio/Phil Collins   Another Day In Paradise.mp3",
  },
  {
    id: 16,
    title: "Wind of Change",
    artist: "Scorpions",
    duration: "2:43",
    src: "./audio/Scorpions   Wind Of Change.mp3",
  },
  {
    id: 17,
    title: "Alors on Danse",
    artist: "Stromae",
    duration: "2:43",
    src: "./audio/Stromae   Alors on Danse.mp3",
  },
  {
    id: 18,
    title: "Africa",
    artist: "Toto",
    duration: "2:43",
    src: "./audio/Toto   Africa.mp3",
  },
  {
    id: 19,
    title: "Tren al Sur",
    artist: "***",
    duration: "2:43",
    src: "./audio/Tren Al Sur.mp3",
  },
  {
    id: 20,
    title: "Stone",
    artist: "Whiskey Mayers",
    duration: "2:43",
    src: "./audio/Whiskey Myers   Stone.mp3",
  },
];